steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t $$USERNAME/data-fetch-app:latest .']
  secretEnv: ['USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $$USERNAME/data-fetch-app:latest']
  secretEnv: ['USERNAME']
availableSecrets:
  secretManager:
  - versionName: projects/gcp-project2-team2/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/gcp-project2-team2/secrets/docker-username/versions/1
    env: 'USERNAME'
