version: '3'

services:
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  python-app:
    build: .
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
      - mysql

mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: datadb
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"


